version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "aws-docker-PAIAssistantAPI"
    IMAGE_TAG: "experimental"
    AWS_ACCOUNT_ID: "365024520127"
    AWS_DEFAULT_REGION: "us-west-2"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - cat /etc/issue
      - uname -a
      - whoami
      - pwd
      - apt update && apt upgrade -y
      - apt -y install curl
      - curl --version
      - python --version
      - apt-cache search libcurl | grep python
      - apt install python3-pycurl
      - echo installing AWS CLI
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli2.zip"
      - unzip -q awscli2.zip
      - ./aws/install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
